import { builtinModules as builtins } from "node:module";
import { Command } from "commander";
import esbuild from "esbuild";
import * as fs from "fs";
import * as path from "path";
import { loadEnvFile } from "process";
import manifest from "./manifest.json" with { type: "json" };
import packageJson from "./package.json" with { type: "json" };

// Initial configuration
if (fs.existsSync(".env")) {
	loadEnvFile(".env");
}

// Parsing command line arguments
const program = new Command();
program
	.option("-p, --production", "Production build")
	.option("-v, --vault [vault]", "Use vault path", false)
	.option("-o, --output-dir <path>", "Output path")
	.option("-b, --beta", "Pre-release version")
	.parse();

// Get options
const options = program.opts();
const isProd = !!options.production;
const isBeta = !!options.beta;
const isStyled = fs.existsSync("src/styles.css");
const pluginID = manifest.id;

// Banner for the output file
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin: ${packageJson.repository}
*/`;

function i18nRefPlugin() {
	return {
		name: "i18n-ref-md",
		setup(build) {
			const refDir = "src/i18n/locales/refs";
			const localeDir = "src/i18n/locales";

			function updateLocales() {
				if (!fs.existsSync(refDir)) return;

				const files = fs.readdirSync(refDir).filter((f) => f.endsWith(".md"));

				for (const file of files) {
					const lang = path.basename(file, ".md");

					const mdPath = path.join(refDir, file);
					const jsonPath = path.join(localeDir, `${lang}.json`);

					if (!fs.existsSync(jsonPath)) continue;

					const markdown = fs.readFileSync(mdPath, "utf8");
					const json = JSON.parse(fs.readFileSync(jsonPath, "utf8"));

					json.refs = markdown;

					fs.writeFileSync(jsonPath, `${JSON.stringify(json, null, 2)}\n`);
				}
			}

			build.onStart(() => {
				updateLocales();
			});

			// watch les .md pour rebuild automatique
			build.onLoad({ filter: /\.md$/ }, async (args) => {
				updateLocales();
				return {
					contents: await fs.promises.readFile(args.path, "utf8"),
					loader: "text",
				};
			});
		},
	};
}

// Determine the output directory based on options
function resolveOutputDir() {
	if (options.outputDir) return options.outputDir;

	if (options.vault) {
		const vaultPath =
			typeof options.vault === "string" ? options.vault : process.env.VAULT;

		if (!vaultPath) throw new Error("VAULT environment variable not set");

		const folderPath = path.join(vaultPath, ".obsidian", "plugins", pluginID);
		if (!fs.existsSync(folderPath)) fs.mkdirSync(folderPath, { recursive: true });

		if (!isProd) fs.writeFileSync(path.join(folderPath, ".hotreload"), "");

		return folderPath;
	}

	return isProd ? "./dist" : "./";
}

// Prepare the output directory
function prepareOutputDir(dir) {
	if ((isProd || options.outputDir) && fs.existsSync(dir)) {
		fs.rmSync(dir, { recursive: true });
	}

	if (isBeta && !fs.existsSync("manifest-beta.json")) {
		fs.copyFileSync("manifest.json", "manifest-beta.json");
	}
}

// Get plugins for esbuild
function getPlugins(outDir) {
	const plugins = [];

	// Plugin pour déplacer les styles
	if (isStyled) {
		plugins.push({
			name: "move-styles",
			setup(build) {
				build.onEnd(() => {
					fs.copyFileSync("src/styles.css", path.join(outDir, "styles.css"));
				});
			},
		});
	}

	// Copy manifest file
	plugins.push({
		name: "copy-manifest",
		setup(build) {
			build.onEnd(() => {
				const manifestSource = isBeta ? "manifest-beta.json" : "manifest.json";
				fs.copyFileSync(manifestSource, path.join(outDir, "manifest.json"));
			});
		},
	});

	plugins.push(i18nRefPlugin());

	return plugins;
}

// Principal configuration
async function buildPlugin() {
	const outDir = resolveOutputDir();
	prepareOutputDir(outDir);

	const entryPoints = ["src/main.ts"];
	if (isStyled) entryPoints.push("src/styles.css");

	// Créer le contexte esbuild
	const context = await esbuild.context({
		banner: { js: banner },
		entryPoints,
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/view",
			"@lezer/common",
			"@lezer/highlight",
			"@lezer/lr",
			...builtins,
		],
		format: "cjs",
		target: "esnext",
		logLevel: "info",
		sourcemap: isProd ? false : "inline",
		treeShaking: true,
		minify: isProd,
		minifySyntax: isProd,
		minifyWhitespace: isProd,
		outdir: outDir,
		plugins: getPlugins(outDir),
	});

	console.log(`🚀 ${isProd ? "Production" : "Development"} build`);
	console.log(`📤 Output directory: ${outDir}`);

	if (isProd) {
		await context.rebuild();
		console.log("✅ Build successful");
		process.exit(0);
	} else {
		await context.watch();
	}
}

buildPlugin().catch((err) => {
	console.error("Build failed:", err);
	process.exit(1);
});
